### PR TITLE
Update scripts to 2018 selectors

### PR DESCRIPTION
**Pull request by matmunn**

### CODE REVIEW

**Comment by atsuya** [comment]
Hello,

Thanks for the pull request. It looks great. I'll test it tomorrow and merge it.

**Comment by atsuya** [comment]
Hi Mat,

I confirm that your updated code works :) I have a question though; does other scripts work?

I can't get play-pause.scpt to work (even after applying the change you made to current-song.scpt), and I'm wondering if it's just me. I'm guessing that Chrome is not allowing external script to run a certain JavaScript code (probably document.dispatchEvent).

**Comment by matmunn** [comment]
I've just confirmed that none of the other scripts seem to be working.
I've changed the script to display the code it's attempting to run and if I copy-paste that code into the chrome console then it works as expected.
I suspect you're right about dispatching events being rejected, since i can also pop alerts from the applescript, but can't get these key events to fire

**Comment by atsuya** [comment]
All scripts seem to work now. Thanks for your great contribution, Mat!

**Pull request merged**
